baseURL = "https://westwood-blog.web.app/"
title = "Westwood Enduro"
theme = "m10c"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Le.Emosapien"
  description = "Motorcycles, japanese food, camping, maps, programming, hiking, whatever...."
  menu_item_separator = " - "
  avatar = "logo.png"
  [[params.social]]
    name = "github"
    url = "https://github.com/emosapien"
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/renograde"

